rename the util class and added into new util package
esoftdigital/identity-service pull request #2
Opened 2024-04-17 18:07 UTC by nageshdivatagi

created new package for util in identity service

2024-04-18 17:38 UTC, esoftdigital requested changes

2024-04-18 17:38 UTC, esoftdigital commented on src/main/java/com/identity/service/util/Util.java
>      public final static short ROLE_FIND_ONE_FLAG = 1;
using same flag for findbyId?

2024-04-18 17:38 UTC, esoftdigital commented on src/main/java/com/identity/service/service/RoleService.java
>  		if (roleList.size() > 0)
check for isEmpty

2024-04-19 05:23 UTC, nageshdivatagi reviewed
currently getByID is not available in store Procedure

2024-04-19 05:23 UTC, nageshdivatagi commented on src/main/java/com/identity/service/service/RoleService.java
>  		if (roleList.size() > 0)
currently getById procedure is not available

2024-04-19 17:47 UTC, esoftdigital approved these changes

2024-04-19 17:48 UTC, merged